INSERT INTO pizza (name, descr, price, photo) VALUES ('Margherita', 'La classica pizza italiana con mozzarella, pomodoro e basilico. Una combinazione semplice ma deliziosa che piace a tutti. Perfetta per chi desidera assaporare i sapori autentici della cucina italiana.', 12.0, 'https://thumbs.dreamstime.com/b/pizza-rustic-italian-mozzarella-cheese-basil-leaves-35669930.jpg');
INSERT INTO pizza (name, descr, price, photo) VALUES ('Perugina', 'Una pizza gourmet con salsiccia italiana di alta qualità e patate fritte croccanti. Un connubio irresistibile di sapori tradizionali e moderne influenze culinarie.', 10.0, 'https://media-cdn.tripadvisor.com/media/photo-s/05/46/77/52/pizza-doppia-moz-salsiccia.jpg');
INSERT INTO pizza (name, descr, price, photo) VALUES ('Quattro Formaggi', 'Un'autentica festa per i formaggi amanti. Questa pizza è generosamente ricoperta di quattro formaggi deliziosi: mozzarella, gorgonzola, parmigiano e provolone. Ogni morso è un tripudio di gusto e cremosità.', 14.0, 'https://cicciopizza.ro/458-large_default/pizza-quattro-formaggi.jpg');
INSERT INTO pizza (name, descr, price, photo) VALUES ('Diavola', 'Una pizza piccante con salame piccante, pomodoro e mozzarella. La combinazione esplosiva di sapori intensi e il tocco di piccantezza renderanno questa pizza una scelta perfetta per gli amanti del gusto forte.', 13.0, 'https://www.misya.info/wp-content/uploads/2007/08/Pizza-alla-diavola.jpg');
INSERT INTO pizza (name, descr, price, photo) VALUES ('Capricciosa', 'Un'esplosione di sapori mediterranei sulla tua pizza! Questa delizia è ricca di funghi freschi, prosciutto cotto, carciofi, olive e mozzarella fusa. Ogni boccone è una combinazione perfetta di dolcezza e salinità.', 15.0, 'https://www.ricettealvolo.it/wp-content/uploads/2023/02/pizza-capricciosa-scaled.jpg');
INSERT INTO pizza (name, descr, price, photo) VALUES ('Hawaiiana', 'Un viaggio culinario verso le isole tropicali. Gusta la combinazione unica di prosciutto cotto dolce, ananas succoso e mozzarella fusa. Questa pizza è una vera e propria festa di sapori esotici.', 12.5, 'https://static01.nyt.com/images/2023/03/29/multimedia/23HAMREX2-pineapple-ham-pizza-qwct/HAMREX2-pineapple-ham-pizza-qwct-superJumbo.jpg');
INSERT INTO pizza (name, descr, price, photo) VALUES ('Vegetariana', 'Una pizza colorata e salutare che soddisferà ogni desiderio vegano e vegetariano. Gusta la freschezza delle verdure miste, accompagnate da pomodoro, mozzarella e aromi mediterranei. Un piatto leggero e saporito per i buongustai consapevoli.', 12.0, 'https://www.fruttaweb.com/consigli/wp-content/uploads/2018/06/pizza-vegana.jpg');
INSERT INTO pizza (name, descr, price, photo) VALUES ('Calzone', 'Un'abbraccio di gusti e sapori racchiusi in un morbido guscio di pizza chiuso. Questa specialità italiana è farcita con mozzarella, pomodoro, salumi e verdure, avvolta in una croccante crosta. Soddisferà la tua voglia di comfort food in ogni morso.', 13.5, 'https://www.allrecipes.com/thmb/Bwkz2gVOQUJcPYSzOJgD94XDi5Q=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/18874-Real-Italian-Calzones-ddmfs-127-4x3-1-a30a0e72801f42bcb0643ed4b57e8a3c.jpg');
INSERT INTO pizza (name, descr, price, photo) VALUES ('Romana', 'La pizza sottile e croccante come la tradizione vuole. Gusta la perfezione dell'impasto leggero, il pomodoro dolce e gli aromi mediterranei. Un classico intramontabile che ti farà sentire come se fossi seduto a un tavolino di una pizzeria di Roma.', 11.0, 'https://www.pizzaontheroad.eu/wp-content/uploads/2019/09/ADL_4586.jpg');
INSERT INTO pizza (name, descr, price, photo) VALUES ('Gorgonzola e Noci', 'Una pizza gourmet che combina il sapore unico del gorgonzola dolce con il croccante delle noci tostate. La delicatezza del formaggio si sposa perfettamente con la ricchezza delle noci, creando una pizza sofisticata e irresistibile.', 13.0, 'https://www.petitchef.it/imgupl/recipe/pizza-al-gorgonzola--450185p695925.jpg');
INSERT INTO pizza (name, descr, price, photo) VALUES ('Marinara', 'La semplicità del gusto italiano in una pizza. Pomodoro fresco, aglio aromatico e origano profumato si fondono per creare un'esperienza culinaria autentica. Un piacere senza fronzoli per gli amanti della cucina tradizionale.', 10.0, 'https://assets.tmecosys.com/image/upload/t_web767x639/img/recipe/ras/Assets/97C2C718-5015-437F-8355-316EE000F57C/Derivates/556409BB-02E0-4BA3-BC16-F409F609FCED.jpg');
INSERT INTO pizza (name, descr, price, photo) VALUES ('Salame', 'Una pizza che sa di tradizione italiana. Gusta la bontà di un salame selezionato, tagliato a fette sottili e disposto con amore sulla tua pizza preferita. Un classico che non deluderà mai.', 11.0, 'https://www.petitchef.it/imgupl/recipe/pizza-al-salame-piccante--455634p707853.jpg');
INSERT INTO pizza (name, descr, price, photo) VALUES ('Salsiccia', 'Una pizza per gli amanti delle carni gustose. La salsiccia italiana, sapientemente condita e cotta, è il protagonista di questa pizza che unisce tradizione e sapore in ogni boccone.', 12.0, 'https://blog.giallozafferano.it/loscrignodelbuongusto/wp-content/uploads/2020/06/5-7.jpg');
INSERT INTO pizza (name, descr, price, photo) VALUES ('Funghi', 'Una pizza che celebra la bontà dei funghi freschi. Gusta l'aroma e la consistenza di funghi champignon o porcini, insieme alla mozzarella filante. Un piacere per i buongustai che amano la semplicità e la delicatezza dei funghi.', 10.5, 'https://www.petitchef.it/imgupl/recipe/pizza-ai-funghi-champignons--452646p700939.jpg');
INSERT INTO pizza (name, descr, price, photo) VALUES ('Tonno', 'Un viaggio di sapori marini sulla tua pizza. Gusta la combinazione di tonno fresco, pomodoro e mozzarella, arricchita da un tocco di prezzemolo fresco. Una scelta leggera e gustosa per i palati che amano il mare.', 11.5, 'https://wips.plug.it/cips/buonissimo.org/cms/2012/05/pizza-con-il-tonno-alla-calabrese.jpg?w=712&a=c&h=406');
INSERT INTO special_offer(pizza_id,start,end,title) VALUES (1, '2023-06-10', '2023-07-10', 'Patate e bibita in omaggio');
INSERT INTO special_offer(pizza_id,start,end,title) VALUES (1, '2023-06-12', '2023-06-25', 'Sconto del 20% sul prezzo');
INSERT INTO special_offer(pizza_id,start,end,title) VALUES (2, '2023-06-15', '2023-06-30', 'Offerta speciale per gli amanti del formaggio');
INSERT INTO special_offer(pizza_id,start,end,title) VALUES (2, '2023-06-18', '2023-07-03', 'Pizza extra grande al prezzo di una piccola');
INSERT INTO special_offer(pizza_id,start,end,title) VALUES (5, '2023-06-20', '2023-07-05', 'Combo famiglia: 2 pizze + 2 bevande');
INSERT INTO special_offer(pizza_id,start,end,title) VALUES (5, '2023-06-22', '2023-07-07', 'Sconto studenti con presentazione di carta studente');
INSERT INTO special_offer(pizza_id,start,end,title) VALUES (7, '2023-06-25', '2023-07-10', 'Offerta per il weekend: 3 pizze al prezzo di 2');
INSERT INTO special_offer(pizza_id,start,end,title) VALUES (8, '2023-06-28', '2023-07-13', 'Consegna gratuita per ordini superiori a $30');
INSERT INTO special_offer(pizza_id,start,end,title) VALUES (9, '2023-07-01', '2023-07-16', 'Sconto del 15% per i nuovi clienti');
INSERT INTO special_offer(pizza_id,start,end,title) VALUES (9, '2023-07-03', '2023-07-18', 'Offerta del giorno: pizza margherita a metà prezzo');
INSERT INTO special_offer(pizza_id,start,end,title) VALUES (9, '2023-07-06', '2023-07-21', '2x1 su tutte le pizze vegetariane');
INSERT INTO special_offer(pizza_id,start,end,title) VALUES (13, '2023-07-08', '2023-07-23', 'Pizza gourmet con 3 ingredienti a scelta');
INSERT INTO special_offer(pizza_id,start,end,title) VALUES (13, '2023-07-11', '2023-07-26', 'Offerta per compleanni: sconto del 25%');
INSERT INTO special_offer(pizza_id,start,end,title) VALUES (15, '2023-07-14', '2023-07-29', 'Pizza senza glutine senza costi aggiuntivi');
INSERT INTO special_offer(pizza_id,start,end,title) VALUES (15, '2023-07-17', '2023-08-01', 'Sconto del 10% per le pizze piccanti');
INSERT INTO ingredient(name) VALUES ('Farina');
INSERT INTO ingredient(name) VALUES ('Zucchero');
INSERT INTO ingredient(name) VALUES ('Uova');
INSERT INTO ingredient(name) VALUES ('Burro');
INSERT INTO ingredient(name) VALUES ('Latte');
INSERT INTO ingredient(name) VALUES ('Sale');
INSERT INTO ingredient(name) VALUES ('Pepe');
INSERT INTO ingredient(name) VALUES ('Olio d'oliva');
INSERT INTO ingredient(name) VALUES ('Aglio');
INSERT INTO ingredient(name) VALUES ('Cipolla');
INSERT INTO ingredient(name) VALUES ('Pomodori');
INSERT INTO ingredient(name) VALUES ('Salsa di soia');
INSERT INTO ingredient(name) VALUES ('Zenzero');
INSERT INTO ingredient(name) VALUES ('Prezzemolo');
INSERT INTO ingredient(name) VALUES ('Basilico');
INSERT INTO ingredient(name) VALUES ('Menta');
INSERT INTO ingredient(name) VALUES ('Limone');
INSERT INTO ingredient(name) VALUES ('Cioccolato');
INSERT INTO ingredient(name) VALUES ('Funghi');
INSERT INTO ingredient(name) VALUES ('Parmigiano');
INSERT INTO pizza_ingredient (pizza_id, ingredient_id) VALUES (1, 1);
INSERT INTO pizza_ingredient (pizza_id, ingredient_id) VALUES (1, 11);
INSERT INTO pizza_ingredient (pizza_id, ingredient_id) VALUES (1, 14);
INSERT INTO pizza_ingredient (pizza_id, ingredient_id) VALUES (2, 1);
INSERT INTO pizza_ingredient (pizza_id, ingredient_id) VALUES (2, 8);
INSERT INTO pizza_ingredient (pizza_id, ingredient_id) VALUES (2, 13);
INSERT INTO pizza_ingredient (pizza_id, ingredient_id) VALUES (3, 1);
INSERT INTO pizza_ingredient (pizza_id, ingredient_id) VALUES (3, 5);
INSERT INTO pizza_ingredient (pizza_id, ingredient_id) VALUES (3, 19);
INSERT INTO pizza_ingredient (pizza_id, ingredient_id) VALUES (4, 1);
INSERT INTO pizza_ingredient (pizza_id, ingredient_id) VALUES (4, 11);
INSERT INTO pizza_ingredient (pizza_id, ingredient_id) VALUES (4, 20);
INSERT INTO pizza_ingredient (pizza_id, ingredient_id) VALUES (5, 1);
INSERT INTO pizza_ingredient (pizza_id, ingredient_id) VALUES (5, 10);
INSERT INTO pizza_ingredient (pizza_id, ingredient_id) VALUES (5, 12);
INSERT INTO pizza_ingredient (pizza_id, ingredient_id) VALUES (6, 1);
INSERT INTO pizza_ingredient (pizza_id, ingredient_id) VALUES (6, 6);
INSERT INTO pizza_ingredient (pizza_id, ingredient_id) VALUES (6, 18);
INSERT INTO pizza_ingredient (pizza_id, ingredient_id) VALUES (7, 1);
INSERT INTO pizza_ingredient (pizza_id, ingredient_id) VALUES (7, 11);
INSERT INTO pizza_ingredient (pizza_id, ingredient_id) VALUES (7, 14);
INSERT INTO pizza_ingredient (pizza_id, ingredient_id) VALUES (7, 16);
INSERT INTO pizza_ingredient (pizza_id, ingredient_id) VALUES (8, 1);
INSERT INTO pizza_ingredient (pizza_id, ingredient_id) VALUES (8, 4);
INSERT INTO pizza_ingredient (pizza_id, ingredient_id) VALUES (8, 10);
INSERT INTO pizza_ingredient (pizza_id, ingredient_id) VALUES (8, 13);
INSERT INTO pizza_ingredient (pizza_id, ingredient_id) VALUES (9, 1);
INSERT INTO pizza_ingredient (pizza_id, ingredient_id) VALUES (9, 11);
INSERT INTO pizza_ingredient (pizza_id, ingredient_id) VALUES (10, 1);
INSERT INTO pizza_ingredient (pizza_id, ingredient_id) VALUES (10, 2);
INSERT INTO pizza_ingredient (pizza_id, ingredient_id) VALUES (10, 5);
INSERT INTO pizza_ingredient (pizza_id, ingredient_id) VALUES (10, 19);
INSERT INTO pizza_ingredient (pizza_id, ingredient_id) VALUES (10, 21);
INSERT INTO pizza_ingredient (pizza_id, ingredient_id) VALUES (11, 1);
INSERT INTO pizza_ingredient (pizza_id, ingredient_id) VALUES (11, 2);
INSERT INTO pizza_ingredient (pizza_id, ingredient_id) VALUES (11, 7);
INSERT INTO pizza_ingredient (pizza_id, ingredient_id) VALUES (11, 11);
INSERT INTO pizza_ingredient (pizza_id, ingredient_id) VALUES (12, 1);
INSERT INTO pizza_ingredient (pizza_id, ingredient_id) VALUES (12, 22);
INSERT INTO pizza_ingredient (pizza_id, ingredient_id) VALUES (13, 1);
INSERT INTO pizza_ingredient (pizza_id, ingredient_id) VALUES (13, 9);
INSERT INTO pizza_ingredient (pizza_id, ingredient_id) VALUES (13, 23);
INSERT INTO pizza_ingredient (pizza_id, ingredient_id) VALUES (14, 1);
INSERT INTO pizza_ingredient (pizza_id, ingredient_id) VALUES (14, 12);
INSERT INTO pizza_ingredient (pizza_id, ingredient_id) VALUES (15, 1);
INSERT INTO pizza_ingredient (pizza_id, ingredient_id) VALUES (15, 11);
INSERT INTO pizza_ingredient (pizza_id, ingredient_id) VALUES (15, 24);
INSERT INTO pizza_ingredient (pizza_id, ingredient_id) VALUES (15, 14);
INSERT INTO roles (id, name) VALUES(1,'ADMIN');
INSERT INTO roles (id, name) VALUES(2,'USER');
INSERT INTO users (id, email, first_name, last_name, password) VALUES(1, 'john@email.com', 'John', 'Doe', '{noop}john');
INSERT INTO users (id, email, first_name, last_name, password) VALUES(2, 'jane@email.com', 'Jane', 'Doe', '{noop}jane');
INSERT INTO users_roles (roles_id, user_id) VALUES(1, 1);
INSERT INTO users_roles (roles_id, user_id) VALUES(2, 2);
